# ***WHAT IS PYTHON LIBRARY?***
A python library is a collection of ready made code - function , classes , modules - that u can reuse in your program instead of writing everything  from scratch 

# **1 - NUMPY**

In [1]:
import math 

print("square root of 2 is", math.sqrt(2))
print(math.atan(45))

square root of 2 is 1.4142135623730951
1.5485777614681775


In [2]:
from datetime import date
t=date.today()
print(t)

2025-10-28


In [39]:
# creating an array
import numpy as priyanshu

a=priyanshu.array([1,2,3,4,5,6])
print(a)
print(type(a))
a

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [43]:
# creating an array
import numpy as np

a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))
a

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [44]:
array2 = np.array([12,23,"If the Plan dosen't work change the plan but never the goal",
                  "Budhist Records of the Western world"])
array2

array(['12', '23',
       "If the Plan dosen't work change the plan but never the goal",
       'Budhist Records of the Western world'], dtype='<U59')

***We can access an individual element of this array as we would access an element in the original int using intger index of the element within the square brackets.***

In [45]:
new_array_1[2]

NameError: name 'new_array_1' is not defined

In [46]:
array2[2]

"If the Plan dosen't work change the plan but never the goal"

In [6]:
a[:3]

array([1, 2, 3])

like the original list the array is immutable 

In [7]:
a[0]=13
a

array([13,  2,  3,  4,  5,  6])

**another difference between a array and alist of lists is that an element of the array can be accesed by specifying the index along each axis within a single set of square brackets separated by commas**

In [8]:
two_dim_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
two_dim_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
two_dim_array[1,3]

8

In [10]:
two_dim_array[1,2]

7

In [14]:
two_dim_1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
two_dim_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
two_dim_1 = np.array([[1,2,],
                     [4,5,6],
                     [7,8,9]])
two_dim_1

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [16]:
two_dim_1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9],
                     [10,11,12],
                     [13,14,15]])
two_dim_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
two_dim_1[:,0]

array([ 1,  4,  7, 10, 13])

In [21]:
two_dim_1[:,2]

array([ 3,  6,  9, 12, 15])

In [29]:
two_dim_1[1:2]

array([[4, 5, 6]])

In [18]:
one_d_array=np.array(67)
one_d_array

array(67)

# Restriction of numpy Array
- all element of the array must be of the same type of data.
- once created the total size of the array cant change
-  **array is an N dimensional array or known as ndarray**

# **Array Attributes**

***ndim:*** The number of dimensions of an array is contained in the ndim attribute.

In [15]:
zero_dim_array = np.array(34)
zero_dim_array.ndim

0

In [16]:
one_dim_array = np.array([1,2,3,4])
one_dim_array.ndim

1

In [17]:
two_dim_array = np.array([[2,3],[4,5]])
two_dim_array.ndim

2

***shape:*** The shape of an array ia a tuple of non-negative integers that quickly the number of elements along each dimensions.

In [18]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


size: The fixed, total number of elements in array is contained in the size attributes.

In [19]:
table_of_2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(table_of_2.size)
print(table_of_2.shape)

10
(2, 5)


***dtype:*** The data type of the elements if the array can be checked using the dtype attributes.

***Note:*** The data type of all the elements of a numpy array is same. i,e. Homegenous

In [20]:
table_of_2.dtype

dtype('int32')

In [21]:
x.dtype

dtype('int32')

In [22]:
x.ndim

2

In [23]:
x.size

6

In [24]:
x.shape

(2, 3)

In [25]:
x[0,]

array([1, 2, 3])

In [26]:
x[:,0]

array([1, 4])

In [27]:
x[1,2]

6

## Same Order Techniques to create an array

The section covers np.zeros(), np.ones(), np.emoty(), np.arange(), np.linspace()

***np.zeros()*** You can create an array filled with zeros.

In [28]:
zero_array = np.zeros(6)
print(zero_array)
print(type(zero_array))
print(zero_array.shape)
print(zero_array.size)

[0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
(6,)
6


In [29]:
# Create a table of zero (2 rows 3 column)

zero_array_table = np.zeros((2,3))
print(zero_array_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
ones_array_2d = np.ones((5,2))
print(ones_array_2d)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


***np.empty()*** This creates an empty array. The elements of an array are randoms and depends on the state of the memory. The reason is an empty over zeros is speed - just make sure to fill every elments afterwards.

In [31]:
empty_array = np.empty(6)
empty_array

array([0., 0., 0., 0., 0., 0.])

***np.arange(start, stop, step)*** Create an array within a range.

In [32]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [33]:
x = np.arange(5,12,2)
x

array([ 5,  7,  9, 11])

***np.linspace(start, stop, step)*** Creates an array with values that are space lineraly in specific integral.

In [34]:
new_array = np.linspace(4,19,20)
new_array

array([ 4.        ,  4.78947368,  5.57894737,  6.36842105,  7.15789474,
        7.94736842,  8.73684211,  9.52631579, 10.31578947, 11.10526316,
       11.89473684, 12.68421053, 13.47368421, 14.26315789, 15.05263158,
       15.84210526, 16.63157895, 17.42105263, 18.21052632, 19.        ])

In [36]:
n_array = np.linspace

# concatenation and sorting of array
this section covers np.sort() , np.concatenate()

### np.sort()

In [1]:
import numpy as np
arr=np.array([2,5,3,8,10,4])
arr_sorted = np.sort(arr)
arr_sorted

array([ 2,  3,  4,  5,  8, 10])

### np.concatenate()

In [2]:
"python"+"data"
[1,2]+[3,4]

[1, 2, 3, 4]

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [4]:
a+b

array([ 6,  8, 10, 12])

In [6]:
# concatenating a and b 
concatenated_array=np.concatenate([b,a])
print(concatenated_array)

[5 6 7 8 1 2 3 4]


In [8]:
# concatenation of 2 .array
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("x: \n",x)
print("y: \n",y)

x: 
 [[1 2]
 [3 4]]
y: 
 [[5 6]
 [7 8]]


In [10]:
# concatenating along axis=0
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.concatenate((x,y),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [12]:
np.concatenate((x,y),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

# RESHAPING OF ARRAY
### arr.reshape

using arr.reshape() will give new shape to an array without changing the data just remember that when you use the reshaape mrthod the you want to produce need to have the same number of element as the origional array . if you start an arrya with 12 element you"ll need to make sure that your new array also has total of 12 element 

In [15]:
import numpy as np
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [16]:
a.shape

(6,)

In [18]:
b=a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [21]:
c=b.reshape(4,1)
c

ValueError: cannot reshape array of size 6 into shape (4,1)

In [22]:
c=b.reshape(6,1)
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [23]:
c=b.reshape(1,6)
c

array([[0, 1, 2, 3, 4, 5]])

In [24]:
c=b.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

# **indexing using condition with array**

In [25]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
print(a[a<5])

[1 2 3 4]


In [28]:
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [29]:
print(a[a%2!=0])

[ 1  3  5  7  9 11]


In [30]:
c=a[(a>2)&(a<11)] #you cannot use and
print(c)

[ 3  4  5  6  7  8  9 10]


In [32]:
c=a[(a>2) and (a<11)] #you cannot use and
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
c=a[(a>2) or (a<11)] #you cannot use or
print(c)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
c=a[(a>2) | (a<11)] #you cannot use or
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
c=a[(a>5) | (a==5)] 
print(c)

[ 5  6  7  8  9 10 11 12]


# ***Basic array operations***
this section covers addition subtraction multiplication , division and more 

In [1]:
import numpy as np

In [2]:
#you can add array together with the + sign 
data1 = np.array([1,2,3])
data2 = np.array([4,5,6])
data1+data2

array([5, 7, 9])

In [4]:
# subtraction
print(data2-data1)

# multiplication
print(data1*data2)

# dvision 
print(data1/data2)

[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## **arr.sum():** sum of all element in an array

In [5]:
a = np.array([1,2,3,4])
a.sum()

10

In [10]:
b = np.array([[1,1],
              [2,2]])
b.sum(axis=0)


array([3, 3])

In [11]:
b.sum(axis=1)

array([2, 4])

# ***Broadcasting***

broadcasting is a mechanism that allow numpy to perform opeation on array of different shapes.

there are many broadcating rules which you can  learn from the numpy documentation 

In [12]:
distance_in_km=np.array([5,2,7,3]) #shape : (4,) dimension:1
single_value=np.array(1000) # shape :() dimension:0
distance_in_km*single_value

array([5000, 2000, 7000, 3000])

In [13]:
print(distance_in_km.shape)
print(single_value.shape)

(4,)
()


In [14]:
print(distance_in_km.ndim)
print(single_value.ndim)

1
0
